### ISSUE TITLE
[QUESTION] XU2 Patcher - Question of integration of fixes into another mod

### ISSUE THREAD

**Issue by Kanzaji** [Darkhax-Minecraft/NoTemaStahp#2]
### Question

Hey there ❤️

I'm here with a bit of a weird question. As of recently, it appears that screens from XU2 stopped working with Tenor API. I've got an request of making a patcher mod for XU2 that will fix the API usage and bring the screens back to life!

While searching if someone didn't do that already I found your's mod and `Extra Utilities Fixes` by quat, both of which do essentially the same thing 😄

I'm currently the maintainer of IC2 Patcher, and will be working on making a patcher mod for XU2, as the license doesn't allow for fixed reuploads (sadly). So I'm here to ask if you would be interested in merging the fixes from your mod into the patcher patches 😅

Thanks for the response in advance and have an awesome day ~Kanz

**Comment by Darkhax** [comment]
Hello,

I don't support older versions of Minecraft any more so feel free to patch the same issues that I patch here in a different project. When I made this project I was avoiding ASM and Mixin so the solutions I came up with aren't the best.

Also what is the Tenor API? The only thing I can find online is the gif hosting website lol.

**Comment by Kanzaji** [comment]
Thanks a lot for the permission ❤️

And big Woops. I meant Imgur API 😅 No idea why I wrote Tenor in the original issue :P
